source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target ’SimpleWeather’ do

pod 'Alamofire', '~> 3.0'
pod 'Realm'
pod 'RealmSwift'
pod 'ReachabilitySwift', :git => 'https://github.com/ashleymills/Reachability.swift'
pod 'Whisper'


end