source 'https://github.com/CocoaPods/Specs.git'

platform :ios, ’10.0’
use_frameworks!

target ’SimpleWeather’ do

pod 'Alamofire', '~> 4.0’
pod 'Realm', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true
pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', branch: 'master', submodules: true

# pod 'Whisper'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = ‘3.0’ # or '3.0'
    end
  end
end